# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('depart', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('hod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('cs', 'Computer Science'), ('EC', 'Electronics and Communication'), ('EEE', 'Electrical and Electronic'), ('Mech', 'Mechanical'), ('BE', 'Biomedial'), ('AS', 'Applied Science'), ('NT', 'Non-Teching')], default='NT', max_length=4)),
                ('Tflag', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='leave_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('leavetype', models.CharField(choices=[('cl', 'casual leave'), ('hp', 'half paid')], max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('recom', models.BooleanField(default=False)),
                ('des', models.CharField(max_length=300)),
                ('half_day', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='leave_statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual', models.IntegerField(default=0)),
                ('vacation', models.IntegerField(default=0)),
                ('conpens', models.IntegerField(default=0)),
                ('earned', models.IntegerField(default=0)),
                ('half_paid', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
