# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('cs', 'Computer Science'), ('EC', 'Electronics and Communication'), ('EEE', 'Electrical and Electronic'), ('Mech', 'Mechanical'), ('BE', 'Biomedial'), ('AS', 'Applied Science'), ('NT', 'Non-Teching')], default='NT', max_length=4)),
                ('Tflag', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
